/**
 * Report Export Service -- generates real downloadable files.
 * Sprint 54.5 -- Production-ready PDF, Excel, CSV, JSON exports.
 */

import { jsPDF } from "jspdf";
import * as XLSX from "xlsx";

export const EXPORT_FORMATS = [
  { id: "pdf", label: "PDF Document", ext: ".pdf", icon: "PictureAsPdf", available: true },
  { id: "xlsx", label: "Excel Spreadsheet", ext: ".xlsx", icon: "TableChart", available: true },
  { id: "csv", label: "CSV File", ext: ".csv", icon: "Description", available: true },
  { id: "json", label: "JSON Data", ext: ".json", icon: "Code", available: true },
  { id: "email", label: "Email Report", ext: null, icon: "Email", available: false },
];

function buildFilename(report, ext) {
  const name = (report.title || "Report").replace(/\s+/g, "_");
  const date = new Date().toISOString().split("T")[0];
  return `${name}_${date}${ext}`;
}

function triggerDownload(blob, filename) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

// ---- PDF Export ----

export function exportPDF(report) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text("Feldrix Control Centre", 14, y);
  doc.text(new Date().toLocaleDateString("en-ZA"), w - 14, y, { align: "right" });
  y += 12;

  // Title
  doc.setFontSize(20);
  doc.setTextColor(15, 23, 42);
  doc.text(report.title || "Report", 14, y);
  y += 8;

  // Meta
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(`Generated: ${new Date(report.generatedAt).toLocaleString("en-ZA")}  |  By: ${report.generatedBy || "Admin"}  |  Version: ${report.version || "1.0"}`, 14, y);
  y += 14;

  // Executive Summary
  doc.setFontSize(12);
  doc.setTextColor(15, 23, 42);
  doc.text("Executive Summary", 14, y);
  y += 7;
  doc.setFontSize(10);
  doc.setTextColor(60);
  const summaryLines = doc.splitTextToSize(report.summary || "No summary available.", w - 28);
  doc.text(summaryLines, 14, y);
  y += summaryLines.length * 5 + 10;

  // KPIs
  if (report.kpis?.length > 0) {
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text("Key Metrics", 14, y);
    y += 7;
    doc.setFontSize(10);
    report.kpis.forEach(kpi => {
      if (y > 270) { doc.addPage(); y = 20; }
      doc.setTextColor(100);
      doc.text(`${kpi.label}:`, 14, y);
      doc.setTextColor(15, 23, 42);
      doc.text(String(kpi.value), 70, y);
      y += 6;
    });
    y += 8;
  }

  // Recommendations
  if (report.recommendations?.length > 0) {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.text("Recommendations", 14, y);
    y += 7;
    doc.setFontSize(10);
    doc.setTextColor(60);
    report.recommendations.forEach(rec => {
      if (y > 270) { doc.addPage(); y = 20; }
      const lines = doc.splitTextToSize(`- ${rec}`, w - 28);
      doc.text(lines, 14, y);
      y += lines.length * 5 + 2;
    });
  }

  // Footer
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text("Generated by Feldrix Control Centre", 14, 290);
    doc.text(`Page ${i} of ${pages}`, w - 14, 290, { align: "right" });
  }

  const filename = buildFilename(report, ".pdf");
  const blob = doc.output("blob");
  triggerDownload(blob, filename);
  return { success: true, filename, format: "pdf" };
}

// ---- Excel Export ----

export function exportExcel(report) {
  const wb = XLSX.utils.book_new();

  // Sheet 1: Summary
  const summaryData = [
    ["Feldrix Control Centre - " + (report.title || "Report")],
    [""],
    ["Generated", new Date(report.generatedAt).toLocaleString("en-ZA")],
    ["Generated By", report.generatedBy || "Admin"],
    ["Version", report.version || "1.0"],
    [""],
    ["Executive Summary"],
    [report.summary || ""],
  ];
  const ws1 = XLSX.utils.aoa_to_sheet(summaryData);
  ws1["!cols"] = [{ wch: 20 }, { wch: 60 }];
  XLSX.utils.book_append_sheet(wb, ws1, "Summary");

  // Sheet 2: KPIs
  if (report.kpis?.length > 0) {
    const kpiData = [["Metric", "Value"], ...report.kpis.map(k => [k.label, k.value])];
    const ws2 = XLSX.utils.aoa_to_sheet(kpiData);
    ws2["!cols"] = [{ wch: 25 }, { wch: 30 }];
    XLSX.utils.book_append_sheet(wb, ws2, "KPIs");
  }

  // Sheet 3: Sections
  if (report.sections?.length > 0) {
    const secData = [["Section"], ...report.sections.map(s => [s])];
    const ws3 = XLSX.utils.aoa_to_sheet(secData);
    XLSX.utils.book_append_sheet(wb, ws3, "Sections");
  }

  // Sheet 4: Recommendations
  if (report.recommendations?.length > 0) {
    const recData = [["Recommendation"], ...report.recommendations.map(r => [r])];
    const ws4 = XLSX.utils.aoa_to_sheet(recData);
    ws4["!cols"] = [{ wch: 80 }];
    XLSX.utils.book_append_sheet(wb, ws4, "Recommendations");
  }

  const filename = buildFilename(report, ".xlsx");
  const wbOut = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  const blob = new Blob([wbOut], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
  triggerDownload(blob, filename);
  return { success: true, filename, format: "xlsx" };
}

// ---- CSV Export ----

export function exportCSV(report) {
  const rows = [];
  rows.push(["Feldrix Control Centre", report.title || "Report"]);
  rows.push(["Generated", new Date(report.generatedAt).toLocaleString("en-ZA")]);
  rows.push(["Generated By", report.generatedBy || "Admin"]);
  rows.push([]);
  rows.push(["Summary", report.summary || ""]);
  rows.push([]);
  if (report.kpis?.length > 0) {
    rows.push(["Metric", "Value"]);
    report.kpis.forEach(k => rows.push([k.label, k.value]));
    rows.push([]);
  }
  if (report.recommendations?.length > 0) {
    rows.push(["Recommendations"]);
    report.recommendations.forEach(r => rows.push([r]));
  }

  const csv = rows.map(r => r.map(c => `"${String(c || "").replace(/"/g, '""')}"`).join(",")).join("\n");
  const blob = new Blob(["\uFEFF" + csv], { type: "text/csv;charset=utf-8" });
  const filename = buildFilename(report, ".csv");
  triggerDownload(blob, filename);
  return { success: true, filename, format: "csv" };
}

// ---- JSON Export ----

export function exportJSON(report) {
  const json = JSON.stringify(report, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  const filename = buildFilename(report, ".json");
  triggerDownload(blob, filename);
  return { success: true, filename, format: "json" };
}

// ---- Master Export Function ----

export function executeExport(report, format) {
  if (!report) return { success: false, error: "No report data" };
  switch (format) {
    case "pdf": return exportPDF(report);
    case "xlsx": return exportExcel(report);
    case "csv": return exportCSV(report);
    case "json": return exportJSON(report);
    default: return { success: false, error: `Format "${format}" not supported` };
  }
}

export function getAvailableFormats() { return EXPORT_FORMATS; }
