-- ============================================================
-- Ground Sampling (Soil Sampling) — Crops module feature
--
-- Additive, tenant-isolated table for recording laboratory soil
-- analysis results against a field (free-text field_name, matching
-- the existing crops.field_name convention) and optionally a crop.
--
-- Units (documented Feldrix standard for v1):
--   ph              : unitless (0–14)
--   nitrogen (N)    : mg/kg (ppm)
--   phosphorus (P)  : mg/kg (ppm)
--   potassium (K)   : mg/kg (ppm)
--   organic_matter  : percent (%)
--   moisture        : percent (%)
--
-- Ownership follows the existing crops RLS pattern exactly:
-- owner-scoped by user_id = auth.uid().
-- No changes to existing tables, policies, or data.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.ground_samples (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  crop_id bigint REFERENCES public.crops(id) ON DELETE SET NULL,
  field_name text,
  sample_date date NOT NULL,
  sampling_depth text,
  ph numeric,
  nitrogen numeric,
  phosphorus numeric,
  potassium numeric,
  organic_matter numeric,
  moisture numeric,
  laboratory text,
  sample_reference text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ground_samples_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.ground_samples IS 'Farmer soil/ground sampling laboratory results. Tenant-isolated by user_id.';
COMMENT ON COLUMN public.ground_samples.nitrogen IS 'Nitrogen (N) in mg/kg (ppm).';
COMMENT ON COLUMN public.ground_samples.phosphorus IS 'Phosphorus (P) in mg/kg (ppm).';
COMMENT ON COLUMN public.ground_samples.potassium IS 'Potassium (K) in mg/kg (ppm).';
COMMENT ON COLUMN public.ground_samples.organic_matter IS 'Organic matter (%).';
COMMENT ON COLUMN public.ground_samples.moisture IS 'Soil moisture (%).';

CREATE INDEX IF NOT EXISTS idx_ground_samples_user_date
  ON public.ground_samples USING btree (user_id, sample_date DESC);
CREATE INDEX IF NOT EXISTS idx_ground_samples_crop
  ON public.ground_samples USING btree (crop_id);

-- Keep updated_at fresh on UPDATE (reuse existing trigger fn if present,
-- otherwise create a dedicated one).
CREATE OR REPLACE FUNCTION public.update_ground_samples_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS ground_samples_updated_at ON public.ground_samples;
CREATE TRIGGER ground_samples_updated_at
  BEFORE UPDATE ON public.ground_samples
  FOR EACH ROW
  EXECUTE FUNCTION public.update_ground_samples_updated_at();

-- ── RLS (mirrors crops policies exactly) ────────────────────
ALTER TABLE public.ground_samples ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own ground samples" ON public.ground_samples;
CREATE POLICY "Users can view their own ground samples"
  ON public.ground_samples FOR SELECT TO public
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own ground samples" ON public.ground_samples;
CREATE POLICY "Users can insert their own ground samples"
  ON public.ground_samples FOR INSERT TO public
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own ground samples" ON public.ground_samples;
CREATE POLICY "Users can update their own ground samples"
  ON public.ground_samples FOR UPDATE TO public
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own ground samples" ON public.ground_samples;
CREATE POLICY "Users can delete their own ground samples"
  ON public.ground_samples FOR DELETE TO public
  USING (auth.uid() = user_id);
