-- ============================================================
-- Rainfall Logging — Weather tab feature
--
-- Additive, tenant-isolated table for FARMER-RECORDED rainfall
-- (measured on the farm). This is deliberately SEPARATE from the
-- weather-service / OpenWeather precipitation data — the two are
-- never mixed.
--
--   amount_mm          : rainfall in millimetres (mm). 0 allowed (dry day).
--   measurement_source : Rain Gauge | Weather Station | Manual Estimate | Other
--   field_name         : free-text, matches the existing crops.field_name convention
--
-- Ownership follows the existing crops/ground_samples RLS pattern
-- exactly: owner-scoped by user_id = auth.uid().
-- No changes to existing tables, policies, or data.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.rainfall_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  rainfall_date date NOT NULL,
  amount_mm numeric NOT NULL,
  field_name text,
  measurement_source text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT rainfall_logs_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.rainfall_logs IS 'Farmer-recorded rainfall measured on the farm. Tenant-isolated by user_id. Separate from weather-service precipitation.';
COMMENT ON COLUMN public.rainfall_logs.amount_mm IS 'Rainfall in millimetres (mm). 0 permitted to record a dry day.';
COMMENT ON COLUMN public.rainfall_logs.measurement_source IS 'Rain Gauge | Weather Station | Manual Estimate | Other';

CREATE INDEX IF NOT EXISTS idx_rainfall_logs_user_date
  ON public.rainfall_logs USING btree (user_id, rainfall_date DESC);
CREATE INDEX IF NOT EXISTS idx_rainfall_logs_user_field
  ON public.rainfall_logs USING btree (user_id, field_name);

-- Keep updated_at fresh on UPDATE (matches project convention).
CREATE OR REPLACE FUNCTION public.update_rainfall_logs_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS rainfall_logs_updated_at ON public.rainfall_logs;
CREATE TRIGGER rainfall_logs_updated_at
  BEFORE UPDATE ON public.rainfall_logs
  FOR EACH ROW
  EXECUTE FUNCTION public.update_rainfall_logs_updated_at();

-- ── RLS (mirrors crops / ground_samples policies exactly) ────
ALTER TABLE public.rainfall_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own rainfall logs" ON public.rainfall_logs;
CREATE POLICY "Users can view their own rainfall logs"
  ON public.rainfall_logs FOR SELECT TO public
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert their own rainfall logs" ON public.rainfall_logs;
CREATE POLICY "Users can insert their own rainfall logs"
  ON public.rainfall_logs FOR INSERT TO public
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update their own rainfall logs" ON public.rainfall_logs;
CREATE POLICY "Users can update their own rainfall logs"
  ON public.rainfall_logs FOR UPDATE TO public
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete their own rainfall logs" ON public.rainfall_logs;
CREATE POLICY "Users can delete their own rainfall logs"
  ON public.rainfall_logs FOR DELETE TO public
  USING (auth.uid() = user_id);
