-- ============================================================
-- Feldrix FarmHand PRO — Production Migration v1.0.0
-- Generated from Development schema on 2026-07-31
-- ============================================================

-- ============================================================
-- TABLES
-- ============================================================

-- 1. profiles (references auth.users)
CREATE TABLE public.profiles (
  id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text,
  email text,
  phone text,
  farm_name text,
  province text,
  farm_size numeric,
  farm_type text DEFAULT 'Mixed Farm'::text,
  weather_alerts boolean DEFAULT true,
  ai_recommendations boolean DEFAULT true,
  weekly_summary boolean DEFAULT true,
  email_notifications boolean DEFAULT true,
  sms_notifications boolean DEFAULT false,
  email_notifications_prefs jsonb,
  avatar_url text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id)
);

-- 2. farms
CREATE TABLE public.farms (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  farm_name text NOT NULL,
  province text,
  farm_size numeric,
  farm_type text DEFAULT 'Mixed Farm'::text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT farms_pkey PRIMARY KEY (id),
  CONSTRAINT farms_owner_unique UNIQUE (owner_id)
);

-- 3. livestock
CREATE TABLE public.livestock (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  tag text NOT NULL,
  breed text,
  gender text,
  weight numeric,
  status text DEFAULT 'Healthy'::text,
  date_of_birth date,
  purchase_date date,
  purchase_price numeric,
  notes text,
  created_at timestamptz DEFAULT now(),
  animal_type text DEFAULT 'Cattle'::text,
  category text,
  CONSTRAINT livestock_pkey PRIMARY KEY (id)
);

-- 4. cattle
CREATE TABLE public.cattle (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE CASCADE,
  animal_name text NOT NULL,
  tag_number text,
  breed text,
  birth_date date,
  weight_kg numeric,
  health_status text DEFAULT 'Healthy'::text,
  vaccination_date date,
  notes text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT cattle_pkey PRIMARY KEY (id)
);

-- 5. animal_health
CREATE TABLE public.animal_health (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  animal_id uuid NOT NULL REFERENCES public.livestock(id) ON DELETE CASCADE,
  treatment_type text NOT NULL,
  medication text,
  treatment_date date NOT NULL,
  next_due date,
  veterinarian text,
  cost numeric DEFAULT 0,
  notes text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT animal_health_pkey PRIMARY KEY (id)
);

-- 6. breeding_records
CREATE TABLE public.breeding_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  female_id uuid NOT NULL REFERENCES public.livestock(id) ON DELETE CASCADE,
  male_id uuid NOT NULL REFERENCES public.livestock(id) ON DELETE CASCADE,
  breeding_date date NOT NULL,
  breeding_method text DEFAULT 'Natural'::text,
  expected_birth date,
  status text DEFAULT 'Bred'::text,
  technician text,
  notes text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT breeding_records_pkey PRIMARY KEY (id)
);

-- 7. weight_history
CREATE TABLE public.weight_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  animal_id uuid NOT NULL REFERENCES public.livestock(id) ON DELETE CASCADE,
  weight numeric NOT NULL,
  recorded_at date NOT NULL DEFAULT CURRENT_DATE,
  notes text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT weight_history_pkey PRIMARY KEY (id)
);

-- 8. crops
CREATE TABLE public.crops (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  crop_name text NOT NULL,
  variety text,
  field_name text,
  planting_date date,
  expected_harvest date,
  area numeric,
  area_unit text DEFAULT 'ha'::text,
  status text DEFAULT 'Growing'::text,
  expected_yield numeric,
  yield_unit text DEFAULT 'kg'::text,
  notes text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT crops_pkey PRIMARY KEY (id)
);

-- 9. crop_plots
CREATE TABLE public.crop_plots (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE CASCADE,
  field_name text NOT NULL,
  crop_type text,
  hectares numeric,
  plant_date date,
  expected_harvest date,
  progress_percent integer DEFAULT 0,
  notes text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT crop_plots_pkey PRIMARY KEY (id)
);

-- 10. machinery
CREATE TABLE public.machinery (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  category text NOT NULL,
  brand text,
  model text,
  registration text,
  purchase_date date,
  purchase_price numeric DEFAULT 0,
  hour_meter integer DEFAULT 0,
  status text DEFAULT 'Active'::text,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT machinery_pkey PRIMARY KEY (id)
);

-- 11. machinery_services
CREATE TABLE public.machinery_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  machine_id uuid REFERENCES public.machinery(id) ON DELETE CASCADE,
  service_type text NOT NULL,
  service_date date NOT NULL,
  hour_meter integer DEFAULT 0,
  cost numeric DEFAULT 0,
  notes text,
  created_at timestamptz DEFAULT now(),
  workshop text,
  invoice_number text,
  CONSTRAINT machinery_services_pkey PRIMARY KEY (id)
);

-- 12. maintenance_plans
CREATE TABLE public.maintenance_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  machine_id uuid NOT NULL REFERENCES public.machinery(id) ON DELETE CASCADE,
  service_type text NOT NULL,
  interval_hours integer NOT NULL,
  next_due_hours integer NOT NULL,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT maintenance_plans_pkey PRIMARY KEY (id)
);

-- 13. finance_records
CREATE TABLE public.finance_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  animal_id uuid REFERENCES public.livestock(id) ON DELETE SET NULL,
  transaction_type text NOT NULL,
  category text NOT NULL,
  amount numeric NOT NULL,
  transaction_date date NOT NULL,
  description text,
  created_at timestamptz DEFAULT now(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  applies_to text DEFAULT 'farm'::text,
  CONSTRAINT finance_records_pkey PRIMARY KEY (id)
);

-- 14. transactions
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  type text NOT NULL,
  category text NOT NULL,
  description text,
  amount numeric NOT NULL,
  transaction_date date NOT NULL,
  payment_method text,
  reference text,
  notes text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id)
);

-- 15. planner_tasks
CREATE TABLE public.planner_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  category text DEFAULT 'General'::text,
  priority text DEFAULT 'Medium'::text,
  status text DEFAULT 'Pending'::text,
  due_date date,
  completed_at timestamptz,
  repeat_type text DEFAULT 'none'::text,
  parent_task_id uuid,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT planner_tasks_pkey PRIMARY KEY (id)
);

-- 16. subscriptions
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  plan text DEFAULT 'free'::text,
  status text DEFAULT 'active'::text,
  billing_cycle text DEFAULT 'monthly'::text,
  price numeric DEFAULT 0,
  renewal_date date,
  payment_provider text,
  payment_reference text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_unique UNIQUE (user_id)
);

-- 17. subscription_payments
CREATE TABLE public.subscription_payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subscription_id uuid,
  amount numeric NOT NULL,
  currency text DEFAULT 'ZAR'::text,
  status text DEFAULT 'pending'::text,
  provider text DEFAULT 'payfast'::text,
  payment_reference text,
  payment_date timestamptz,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT subscription_payments_pkey PRIMARY KEY (id)
);

-- 18. payments
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  subscription_id uuid,
  provider text NOT NULL,
  transaction_id text,
  amount numeric,
  currency text DEFAULT 'ZAR'::text,
  status text,
  payment_date timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id)
);

-- 19. tasks (farm tasks, legacy)
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text,
  due_date date,
  status text DEFAULT 'Pending'::text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT tasks_pkey PRIMARY KEY (id)
);

-- 20. activity_logs
CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  owner_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  farm_id uuid NOT NULL REFERENCES public.farms(id) ON DELETE CASCADE,
  category text,
  description text,
  created_at timestamptz DEFAULT now(),
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id)
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_machinery_user ON public.machinery USING btree (user_id);
CREATE INDEX idx_machinery_category ON public.machinery USING btree (category);
CREATE INDEX idx_machinery_status ON public.machinery USING btree (status);
CREATE INDEX idx_machine_services_machine ON public.machinery_services USING btree (machine_id);
CREATE INDEX idx_machine_services_date ON public.machinery_services USING btree (service_date);
CREATE INDEX idx_maintenance_plans_machine ON public.maintenance_plans USING btree (machine_id);
CREATE INDEX idx_maintenance_plans_service ON public.maintenance_plans USING btree (service_type);
CREATE INDEX idx_planner_parent ON public.planner_tasks USING btree (parent_task_id);
CREATE INDEX idx_planner_tasks_user_due ON public.planner_tasks USING btree (user_id, due_date);
CREATE INDEX idx_planner_repeat_type ON public.planner_tasks USING btree (repeat_type);
CREATE INDEX idx_subscription_payments_user ON public.subscription_payments USING btree (user_id);
CREATE INDEX idx_weight_history_animal ON public.weight_history USING btree (animal_id);

-- ============================================================
-- FUNCTIONS
-- ============================================================

CREATE OR REPLACE FUNCTION public.update_planner_tasks_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
begin
    new.updated_at = now();
    return new;
end;
$$;

CREATE OR REPLACE FUNCTION public.update_subscriptions_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
begin
    new.updated_at = now();
    return new;
end;
$$;

-- ============================================================
-- TRIGGERS
-- ============================================================

CREATE TRIGGER planner_tasks_updated_at
  BEFORE UPDATE ON public.planner_tasks
  FOR EACH ROW
  EXECUTE FUNCTION public.update_planner_tasks_updated_at();

CREATE TRIGGER trigger_update_subscriptions_updated_at
  BEFORE UPDATE ON public.subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION public.update_subscriptions_updated_at();

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

-- Enable RLS on all tables (breeding_records intentionally left without RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.farms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.livestock ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cattle ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.animal_health ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weight_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crops ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.crop_plots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.machinery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.machinery_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finance_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planner_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subscription_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- RLS POLICIES
-- ============================================================

-- profiles
CREATE POLICY "Users can create their own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = id);
CREATE POLICY "Users insert own profile" ON public.profiles FOR INSERT TO public WITH CHECK (auth.uid() = id);
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE TO public USING (auth.uid() = id);
CREATE POLICY "Users view own profile" ON public.profiles FOR SELECT TO public USING (auth.uid() = id);

-- farms
CREATE POLICY "Users manage own farms" ON public.farms FOR ALL TO public USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

-- livestock
CREATE POLICY "Users can view own livestock" ON public.livestock FOR SELECT TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own livestock" ON public.livestock FOR INSERT TO public WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own livestock" ON public.livestock FOR UPDATE TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own livestock" ON public.livestock FOR DELETE TO public USING (auth.uid() = user_id);

-- cattle
CREATE POLICY "Users manage own cattle" ON public.cattle FOR ALL TO public USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

-- animal_health
CREATE POLICY "Users can view own health records" ON public.animal_health FOR SELECT TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own health records" ON public.animal_health FOR INSERT TO public WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own health records" ON public.animal_health FOR UPDATE TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own health records" ON public.animal_health FOR DELETE TO public USING (auth.uid() = user_id);

-- weight_history (open access — filtered by app logic via animal_id join)
CREATE POLICY "Users can view their own weight history" ON public.weight_history FOR SELECT TO public USING (true);
CREATE POLICY "Users can insert weight history" ON public.weight_history FOR INSERT TO public WITH CHECK (true);
CREATE POLICY "Users can update weight history" ON public.weight_history FOR UPDATE TO public USING (true);
CREATE POLICY "Users can delete weight history" ON public.weight_history FOR DELETE TO public USING (true);

-- crops
CREATE POLICY "Users can view their own crops" ON public.crops FOR SELECT TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own crops" ON public.crops FOR INSERT TO public WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own crops" ON public.crops FOR UPDATE TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own crops" ON public.crops FOR DELETE TO public USING (auth.uid() = user_id);

-- crop_plots
CREATE POLICY "Users manage own crop plots" ON public.crop_plots FOR ALL TO public USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

-- machinery
CREATE POLICY "Users can view own machinery" ON public.machinery FOR SELECT TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own machinery" ON public.machinery FOR INSERT TO public WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own machinery" ON public.machinery FOR UPDATE TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own machinery" ON public.machinery FOR DELETE TO public USING (auth.uid() = user_id);

-- machinery_services (owner-through-machinery check)
CREATE POLICY "Users can view machinery services" ON public.machinery_services FOR SELECT TO public
  USING (EXISTS (SELECT 1 FROM machinery WHERE machinery.id = machinery_services.machine_id AND machinery.user_id = auth.uid()));
CREATE POLICY "Users can insert machinery services" ON public.machinery_services FOR INSERT TO public
  WITH CHECK (EXISTS (SELECT 1 FROM machinery WHERE machinery.id = machinery_services.machine_id AND machinery.user_id = auth.uid()));
CREATE POLICY "Users can update machinery services" ON public.machinery_services FOR UPDATE TO public
  USING (EXISTS (SELECT 1 FROM machinery WHERE machinery.id = machinery_services.machine_id AND machinery.user_id = auth.uid()));
CREATE POLICY "Users can delete machinery services" ON public.machinery_services FOR DELETE TO public
  USING (EXISTS (SELECT 1 FROM machinery WHERE machinery.id = machinery_services.machine_id AND machinery.user_id = auth.uid()));

-- maintenance_plans (owner-through-machinery check)
CREATE POLICY "Users can view maintenance plans" ON public.maintenance_plans FOR SELECT TO public
  USING (EXISTS (SELECT 1 FROM machinery WHERE machinery.id = maintenance_plans.machine_id AND machinery.user_id = auth.uid()));
CREATE POLICY "Users can insert maintenance plans" ON public.maintenance_plans FOR INSERT TO public
  WITH CHECK (EXISTS (SELECT 1 FROM machinery WHERE machinery.id = maintenance_plans.machine_id AND machinery.user_id = auth.uid()));
CREATE POLICY "Users can update maintenance plans" ON public.maintenance_plans FOR UPDATE TO public
  USING (EXISTS (SELECT 1 FROM machinery WHERE machinery.id = maintenance_plans.machine_id AND machinery.user_id = auth.uid()));
CREATE POLICY "Users can delete maintenance plans" ON public.maintenance_plans FOR DELETE TO public
  USING (EXISTS (SELECT 1 FROM machinery WHERE machinery.id = maintenance_plans.machine_id AND machinery.user_id = auth.uid()));

-- finance_records
CREATE POLICY "Users manage own finance records" ON public.finance_records FOR ALL TO public USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- transactions
CREATE POLICY "Users can view own transactions" ON public.transactions FOR SELECT TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own transactions" ON public.transactions FOR INSERT TO public WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own transactions" ON public.transactions FOR UPDATE TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own transactions" ON public.transactions FOR DELETE TO public USING (auth.uid() = user_id);

-- planner_tasks
CREATE POLICY "Users can view own planner tasks" ON public.planner_tasks FOR SELECT TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own planner tasks" ON public.planner_tasks FOR INSERT TO public WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own planner tasks" ON public.planner_tasks FOR UPDATE TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own planner tasks" ON public.planner_tasks FOR DELETE TO public USING (auth.uid() = user_id);

-- subscriptions
CREATE POLICY "Users can view own subscription" ON public.subscriptions FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "Users can create own subscription" ON public.subscriptions FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own subscription" ON public.subscriptions FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- subscription_payments
CREATE POLICY "Users can view their own payments" ON public.subscription_payments FOR SELECT TO public USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own payments" ON public.subscription_payments FOR INSERT TO public WITH CHECK (auth.uid() = user_id);

-- tasks
CREATE POLICY "Users manage own tasks" ON public.tasks FOR ALL TO public USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

-- activity_logs
CREATE POLICY "Users manage own activity logs" ON public.activity_logs FOR ALL TO public USING (auth.uid() = owner_id) WITH CHECK (auth.uid() = owner_id);

-- ============================================================
-- GRANT PERMISSIONS (required for Supabase anon/authenticated access)
-- ============================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL ROUTINES IN SCHEMA public TO anon, authenticated;
